[BLOG]-add-making-gpus-accessible-to-pydata-ecosystem-via-array-api
Quansight/Quansight-website pull request #246
Opened 2022-06-22 09:37 UTC by noatamir

## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [x] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If it were to be read as plain text, the blog still makes sense and no information is missing.

## Links to other Quansight blogs: 
https://labs.quansight.org/blog/2021/11/pydata-extensibility-vision/
no llc links found
☝️ this will be tweaked after the migration of this blog.
New link: https://labs.quansight.org/library/blog/2021/11/pydata-extensibility-vision/

2022-06-30 15:04 UTC, gabalafou requested changes
The only things that should be fixed before merging in:

- The AMD logo image at the bottom of the blog post.

We also need to decide whether or not to keep my commit that fixes the heading levels so they are compliant with axe-core accessibility checks.

2022-06-30 15:04 UTC, gabalafou commented on apps/labs/posts/making-gpus-accessible-to-pydata-ecosystem-via-array-api.md
> +```python
The code blocks have syntax highlighting, but the highlighting has contrast accessibility issues. Note to self to create GitHub issue about this.

2022-07-02 12:50 UTC, noatamir commented on apps/labs/posts/making-gpus-accessible-to-pydata-ecosystem-via-array-api.md
> +     src="/images/sponsors/AMD_E_Blk_RGB.png"
fixed

2022-07-05 08:25 UTC, gabalafou approved these changes
Approved. Just FYI, I added some merge commits to this PR's branch in order to make the preview build URL work. Not sure if you want to clean those up (squash merge?) or merge as-is. Whatever works :)

2022-07-05 09:47 UTC, gabalafou commented
You can access a rendered version of this blog post on Vercel at the following URL: https://quansight-labs-published-e4brof80w-quansight.vercel.app/blog/making-gpus-accessible-to-pydata-ecosystem-via-array-api

2022-07-06 10:18 UTC, merged