[BLOG] Add what-do-we-need-to-write.md
Quansight/Quansight-website pull request #278
Opened 2022-07-01 12:24 UTC by MarsBarLee

## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [x] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If it were to be read as plain text, the blog still makes sense and no information is missing.

## Links to other Quansight blogs:
no labs links found
no llc links found

2022-07-02 11:25 UTC, noatamir commented
@gabalafou CC @trallard 
- this blog is failing on missing author. 
- All the authors are in storyblok and have images. 
- I am not sure if I should put multiple authors in brackets or quotes 
- There is no guidance in the readme.

2022-07-05 10:02 UTC, gabalafou reviewed
This PR is almost ready to merge. Just have to fix the issue with multiple authors.

2022-07-05 10:02 UTC, gabalafou commented on apps/labs/posts/what-do-we-need-to-write.md
> +author: tania-allard, melissa-mendonca, isabela-presedo-floyd, rohit-goswami, tony-fast, dillon-roach, dharhas-pothina, eric-kelly
@noatamir you're already aware of this, I think, but multiple authors seems not supported at the moment. This line causes the build to fail. I'm not sure what we should do. cc @trallard

2022-07-05 17:43 UTC, gabalafou requested changes
I suggest that we modify the author field to just have Isabela and push the other authors to one line at the beginning.

2022-07-05 17:43 UTC, gabalafou commented on apps/labs/posts/what-do-we-need-to-write.md
> +author: tania-allard, melissa-mendonca, isabela-presedo-floyd, rohit-goswami, tony-fast, dillon-roach, dharhas-pothina, eric-kelly
```suggestion
author: isabela-presedo-floyd
```

2022-07-12 12:46 UTC, gabalafou commented on apps/labs/posts/what-do-we-need-to-write.md
> +Additional authors: Tania Allard, Melissa Mendonça, Rohit Goswami, Tony Fast, Dillon Roach, Dharhas Pothina, Eric Kelly.
```suggestion
Additional authors: Tania Allard, Melissa Mendonça, Rohit Goswami, Tony Fast, Dillon Roach, 
Dharhas Pothina, Eric Kelly.

```

2022-07-12 12:46 UTC, merged