Add orientation section and use release branches
Quansight/Quansight-website pull request #433
Opened 2022-08-31 15:23 UTC by gabalafou

2022-08-31 16:28 UTC, bskinn requested changes
@gabalafou  Anyone conversant in git will probably not need this detail, but I think it'd be wise to include.

2022-08-31 16:28 UTC, bskinn commented on README.md
> +   git push
Have to link the remote in the push

```suggestion
   git push -u origin release-YYYYMMDD
```

2022-08-31 17:06 UTC, gabalafou commented on README.md
> +message](slack://user?team=T8XM7KN5B&id=U02JA56KDDY).
```suggestion
environment variables. <a href="slack://user?team=T8XM7KN5B&id=U02JA56KDDY">Open Slack direct
message</a>
```

2022-09-01 00:09 UTC, bskinn approved these changes
All seems ok to me with the new changes.

2022-09-01 11:07 UTC, merged