[BLOG] Add the-new-spyder-editor-documentation-under-the-spotlights.md
Quansight/Quansight-website pull request #536
Opened 2022-10-28 02:36 UTC by hyounes4560

## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [x] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If it were to be read as plain text, the blog still makes sense and no information is missing.

2022-11-02 15:42 UTC, noatamir commented
@hyounes4560 the blog preview works now. For some reason, the hero image is showing up as white. I was looking at your documentation link and saw you have plenty of great screenshots in there. Would you like to maybe use one or two of those for the blog? You just need to crop them for the hero and feature image sizes: hero 1440x696 pixels, feature 391x174 pixels. If not that ok, please let us know, and we can investigate, why the current hero svg isn't displaying correctly.

2022-11-02 15:54 UTC, noatamir commented on apps/labs/posts/the-new-spyder-editor-documentation-under-the-spotlights.md
> +  imageSrc: /posts/what-do-we-need-to-write/blog_hero_var3.svg
I think the path here is mis-specified 😉  If you update the folder name the hero appear.

2022-11-03 22:25 UTC, steff456 requested changes
I left a minor comment, but the blog post looks great!

2022-11-03 22:25 UTC, steff456 commented on apps/labs/posts/the-new-spyder-editor-documentation-under-the-spotlights.md
> +During the past 6 months, I, my mentor for this program "Stephannie Jiménez",
I think we can remove the quotes here.

```suggestion
During the past 6 months, I, my mentor for this program Stephannie Jiménez,
```

2022-11-14 11:34 UTC, noatamir commented on apps/labs/posts/nebari-typer-cli.md
> +published: November 7, 2022
```suggestion
published: November 15, 2022
```

2022-11-14 11:35 UTC, noatamir commented on apps/labs/posts/nebari-typer-cli.md
> +published: November 7, 2022
update published date

2022-11-14 11:35 UTC, noatamir commented on apps/labs/posts/the-new-spyder-editor-documentation-under-the-spotlights.md
> +published: October 31, 2022
```suggestion
published: Nevomeber 15, 2022
```

2022-11-15 14:00 UTC, noatamir approved these changes
LGTM

2022-11-15 14:07 UTC, merged