[BLOG] Add python-moa-introduction
Quansight/Quansight-website pull request #633
Opened 2023-01-23 21:06 UTC by MarsBarLee

Link to [blog post, successful build](https://labs-git-python-moa-introduction-quansight.vercel.app/blog/python-moa-introduction).

## Links to other Quansight blogs:
There is no need to check for Blog2Blog links due to updated website build. 
## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [x] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If it were to be read as plain text, the blog still makes sense and no information is missing.

2023-02-01 19:28 UTC, MarsBarLee commented
This is one the ipynb-to-md conversion. There's about 10 more to post.

2023-02-14 17:10 UTC, gabalafou commented
I changed the feature image for variation:

<img width="919" alt="" src="https://user-images.githubusercontent.com/317883/218808154-cb9785f2-9a0a-4543-b276-e00ea693a5bc.png">

2023-02-14 17:53 UTC, gabalafou approved these changes

2023-02-14 17:58 UTC, gabalafou requested changes

2023-02-14 17:58 UTC, gabalafou commented on apps/labs/posts/python-moa-introduction.md
> +        return _a19
[Indented code does not work in MDX](https://mdxjs.com/docs/what-is-mdx/#markdown).

Also, this looks like output to me, so we have the same issue here that we have described before:

- https://github.com/Quansight/Quansight-website/pull/647#pullrequestreview-1279809159

2026-02-02 12:36 UTC, merged