Release 2023-10-17
Quansight/Quansight-website pull request #793
Opened 2023-10-17 18:43 UTC by pavithraes

Merge `develop` into `main`

2023-10-17 18:52 UTC, pavithraes commented
Everything looks good to me:
- New labs blogs are rendered:
	- [Doctesting for PyData libraries](https://labs-git-release-20231017-quansight.vercel.app/blog/doctesting-for-pydata-libraries)
	- [Hypothesis testing in SymPy](https://labs-git-release-20231017-quansight.vercel.app/blog/integrating-hypothesis-into-sympy) 
- Labs blog updates:
	-  [SciPy array API](https://labs-git-release-20231017-quansight.vercel.app/blog/scipy-array-api) -- the SVG hero image is rendered correctly
- Optimized images across the site look fine (did not verify each one, just a couple)
- [Labs team page](https://labs-git-release-20231017-quansight.vercel.app/team) updates are reflected (Mars, Thomas F, Pamphile removed; and Mateusz, Isuru added)

2023-10-17 19:36 UTC, bskinn commented on apps/labs/CHANGELOG.md
> +- Added Mateusz Sokół (switch Role from `author` to `team`) and Isuru Fernandoto (newly added) to the team page
Was this part of the typo that needed fixing, @pavithraes?

```suggestion
- Added Mateusz Sokół (switch Role from `author` to `team`) and Isuru Fernando (newly added) to the team page
```

2023-10-17 20:02 UTC, bskinn requested changes
General proofing pass on Diane's post.

There's enough here that I think we should hotfix in the release branch, @pavithraes, and then back-merge to `develop` after the merge to `main`.

2023-10-17 20:02 UTC, bskinn commented on apps/labs/posts/integrating-hypothesis-into-sympy.md
> +Hypothesis is now a required _testing_ dependency of SymPy. Property based tests can be created in the `test_hypothesis.py` file in respective tests directories more details in the [new contributor d
```suggestion
Hypothesis is now a required _testing_ dependency of SymPy. Property based tests can be created in a `test_hypothesis.py` file in the appropriate test directories (more details in the [new contributor documentation](https://github.com/sympy/sympy/blob/master/doc/src/contributing/new-contributors-guide/writing-tests.md#hypothesis-testing)). An example testing file using Hypothesis can be found in [ntheory/tests](https://github.com/sympy/sympy/blob/master/sympy/ntheory/tests/test_hypothesis.py).
```

2023-10-17 20:02 UTC, bskinn commented on apps/labs/posts/integrating-hypothesis-into-sympy.md
> +- There were various issues with the lowest common multiple (LCM) function (notes in [issue#25624](https://github.com/sympy/sympy/issues/25624), [PR#25636](https://github.com/sympy/sympy/pull/25636),
I'd normally expect to see spaces here

```suggestion
- There were various issues with the lowest common multiple (LCM) function (notes in [issue #25624](https://github.com/sympy/sympy/issues/25624), [PR #25636](https://github.com/sympy/sympy/pull/25636), and [PR #25517](https://github.com/sympy/sympy/pull/25517#issuecomment-1714474991)), the biggest being when the LCM should make use of the integer implementation vs polynomial implementation (when the defined polynomial is essentially an integer).
```

2023-10-24 15:14 UTC, bskinn commented
Friendly reminder, @pavithraes, this release is waiting on review of this proofing pass.

2023-10-24 15:17 UTC, bskinn commented
Or, @melissawm, if you have more bandwidth for reviewing these few fixes/suggestions.

2023-10-30 18:58 UTC, melissawm approved these changes
Couldn't find anything beyond your comments, @bskinn - this looks good to me with your changes. Thank you!

2023-10-30 19:35 UTC, bskinn approved these changes
Edits are approved, I believe we are ready to merge to live.

2023-10-30 20:33 UTC, bskinn reviewed
Update pub dates

2023-10-30 20:33 UTC, bskinn commented on apps/labs/posts/doctesting-for-pydata-libraries.md
> +published: September 30, 2023
```suggestion
published: October 30, 2023
```

2023-10-30 20:33 UTC, bskinn commented on apps/labs/posts/integrating-hypothesis-into-sympy.md
> +published: September 20, 2023
```suggestion
published: October 30, 2023
```

2023-10-30 20:42 UTC, merged