Pycont lit 2024
Quansight/Quansight-website pull request #841
Opened 2024-04-09 11:28 UTC by MarcoGorelli

## Text styling

- [ ] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [ ] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [ ] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [ ] Blog post featured image is in PNG or JPEG format, **not** SVG.
- [ ] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If it were to be read as plain text, the blog still makes sense and no information is missing.

2024-05-21 15:59 UTC, rgommers requested changes
Thanks Marco. This is a nice high-level story. A few suggestions, both content-wise and copy-editing.

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +published: April 9, 2024
```suggestion
published: May 21, 2024
```

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +I attended PyConLithuania 2024, and had a blast! I don't speak Lithuanian, and probably
```suggestion
I attended PyCon Lithuania 2024, and had a blast! I don't speak Lithuanian, and probably
```

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +to print `'True'` - but no so! pandas checks if `3` is in the index, whereas Polars checks
```suggestion
to print `'True'` - but not so! pandas checks if `3` is in the index, whereas Polars checks
```

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +have typically to such diversity is to support pandas...
```suggestion
typically have to such diversity is to support only pandas...
```

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +## pandas are everywhere
```suggestion
## pandas is everywhere
```

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +[a little tutorial](https://marcogorelli.github.io/narwhals/basics/complete_example/).
this link is broken, as are the other ones to this site

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +meaning that libraries can become compatible without having to asking any other library
```suggestion
meaning that libraries can become compatible without having to ask any other library
```

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +then Narwhals is currently (as of April 2024) a more realistic solution - Ibis alone (310 MB) would put you above
"Ibis alone" should probably state that it's Ibis plus all its required dependencies?

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +![Image relative sizes of Narwhals (0.3 MB) vs Ibis (310 MB)](/posts/dataframe-interop-pycon-lit-2024/narwhals_vs_ibis.png)
This image is very rough, I suggest to remove it.

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +Note that the projects are not in competition and have different goals.
This leaves the reader wondering quite a bit. Maybe add one sentence for each?

2024-05-21 15:59 UTC, rgommers commented on apps/labs/posts/dataframe-interop-pycon-lit-2024.md
> +  pandas 3.0+. For now, however, if you're using the interchange protocol to convert
```suggestion
 pandas 3.0. For now, however, if you're using the interchange protocol to convert
```

2024-05-27 13:59 UTC, MarcoGorelli commented
thanks Ralf for your review! I think I've addressed all comments, and I removed the Ibis comparison entirely

2024-05-27 18:31 UTC, rgommers approved these changes
Looks good to me now, thanks Marco! In it goes 🚀

2024-05-27 18:31 UTC, merged