[BLOG] Create Accouncing Scientific Python Accessibility Events
Quansight/Quansight-website pull request #875
Opened 2024-09-02 05:47 UTC by isabela-pf

## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- x ] Blog post featured image is in PNG or JPEG format, **not** SVG.
- [x] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If it were to be read as plain text, the blog still makes sense and no information is missing.

2024-09-02 11:49 UTC, trallard commented on apps/labs/posts/announcing-scientific-python-accessibility-events.md
> +For anyone who spends part of their day online, figuring out how to incorporate accessibility can leave many question marks. Advice, if you can find it all, is often vague enough or detailed enough t
```suggestion
For anyone who spends part of their day online, figuring out how to incorporate accessibility can leave many question marks, including how to get started. If you can find it all, advice is often vague enough or detailed enough to make action impossible. This event is designed to align practical examples of day-to-day digital activities—like making a calendar invite or sending things to your friends—with small habits that can make identifying and remedying accessibility pitfalls clear. All in the style of a choose-your-own-adventure story with audience polling!
```

2024-09-02 21:47 UTC, isabela-pf commented
Rewording accepted and registration links added. Please let me know if you notice any other issues.

2024-09-03 15:10 UTC, gabalafou requested changes
I left a few copy suggestions, feel free to incorporate or not, as you think best.

There are a few unrelated changes in this PR that need to be removed before merging. I will fix it up for you.

2024-09-03 15:10 UTC, gabalafou commented on apps/labs/posts/announcing-scientific-python-accessibility-events.md
> +For anyone who spends part of their day online, figuring out how to incorporate accessibility can leave many question marks, including how to get started. If you can find it all, advice is often vagu
```suggestion
For anyone who spends part of their day online, figuring out how to incorporate accessibility can leave many question marks, including how to get started. If you can find it at all, advice is often vague enough (or so overwhelmingly detailed) to make action impossible. This event is designed to align practical examples of day-to-day digital activities—like making a calendar invite or sending things to your friends—with small habits that can make identifying and remedying accessibility pitfalls clear. All in the style of a choose-your-own-adventure story with audience polling!
```

2024-09-03 15:10 UTC, gabalafou commented on apps/labs/posts/announcing-scientific-python-accessibility-events.md
> +Data visualization is a varied and often complex topic that draws on many disciplines. Many have advised on ways to make data visualizations include more options for people who are blind and low visi
```suggestion
Data visualization is a varied and complex topic that draws on many disciplines. Many have advised on ways to make data visualizations more inclusive of people who are blind or low vision and/or deaf or hard of hearing. This event will compile existing recommendations to provide an abbreviated guide to the what and why behind making data visualizations available to more people.
```

2024-09-03 15:10 UTC, gabalafou commented on apps/labs/posts/announcing-scientific-python-accessibility-events.md
> +  alt: 'A tree branch extends from the screen of a laptop with a bar chart.'
```suggestion
  alt: 'A tree branch extends from a laptop screen. There is a bar chart on the screen.'
```

2024-09-10 07:18 UTC, isabela-pf commented
Just checking on this! I believe I've reviewed all the changes and that @gabalafou has kindly corrected the mis-caught commits. Please let me know if there's anything else I need to do to help the blog post progress.

2024-09-10 17:06 UTC, trallard approved these changes

2024-09-10 17:07 UTC, gabalafou approved these changes

2024-09-10 17:07 UTC, merged