[BLOG] Added blog post for enhancing developer experience at SciPy - Intel oneAPI, MSVC and spin support
Quansight/Quansight-website pull request #893
Opened 2024-12-19 07:37 UTC by czgdp1807

## Text styling

- [ ] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [ ] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [ ] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [ ] Blog post featured image is in PNG or JPEG format, **not** SVG.
- [ ] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If it were to be read as plain text, the blog still makes sense and no information is missing.

2024-12-19 07:47 UTC, czgdp1807 commented
The blog preview is https://labs-ksnzv1tzf-quansight.vercel.app/blog/intel-oneapi-msvc-spin-scipy. All the content is as it is (`asciinema` videos are also there in their respective places).

2024-12-19 07:50 UTC, czgdp1807 reviewed
Also, I have SciPy logo as featured and hero images. I hope that should work because its 100% SciPy work.

2024-12-19 07:50 UTC, czgdp1807 commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +title: 'Enhancing Developer Experience at SciPy - Intel oneAPI/MSVC Support and Migrating to `spin`'
Should I remove, "\`" from "`spin`"?

2024-12-22 07:00 UTC, czgdp1807 commented
I have shortened the links. However at some places (very few) I had to use PR titles so I put the title inside "\`" and linked the issue \[\[pr_number\]\]\(pr_link\). That way the link is short. Please let me know if any other changes are needed.

2024-12-22 07:10 UTC, czgdp1807 commented
I checked the preview - https://labs-pu7mgao24-quansight.vercel.app - everything loads correctly (`asciinema` videos and the text of the blog). See the screenshots below. I have zoomed out to cover the whole page in screenshot.

<details>

<summary>Screenshots of `asciinema` videos loading correctly</summary>

<img width="1352" alt="Screenshot 2024-12-22 at 12 35 33 PM" src="https://github.com/user-attachments/assets/01b3e851-1a00-43dc-ae7c-4151cc85b7ba" />
<img width="1352" alt="Screenshot 2024-12-22 at 12 35 45 PM" src="https://github.com/user-attachments/assets/8dd60f16-a7f5-4cb8-a31b-067d67723e28" />
<img width="1352" alt="Screenshot 2024-12-22 at 12 35 56 PM" src="https://github.com/user-attachments/assets/4f8a3c50-66de-4012-a51c-7489201b2c91" />
<img width="1352" alt="Screenshot 2024-12-22 at 12 36 10 PM" src="https://github.com/user-attachments/assets/2a7f4faf-8c4a-4e5a-87c7-7b831180f8a7" />
<img width="1352" alt="Screenshot 2024-12-22 at 12 36 22 PM" src="https://github.com/user-attachments/assets/536241a6-121a-41ca-ab70-a30c4e63dbd3" />

</details>

2025-02-14 13:19 UTC, rgommers reviewed
Thanks @czgdp1807. A set of inline comments. Can you please line-break the content at 80 chars or so? That's way easier to review line by line.

2025-02-14 13:19 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +The above video showcases how `spin` works fine with Homebrew installed Python 3.10. The build completes. However, `dev.py` fails because it is unable to resolve paths correctly.
It would be good to add acknowledgements - this was done with NASA funding. Can you please copy the phrasing at the end of Albert's recent blog post for this?

2025-02-14 13:19 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Intel offers oneAPI - a complete toolkit for HPC use cases. It has ICX (for C), ICPX (for C++), IFX (for Fortran) and MKL (an OpenBLAS alternative). We targeted two operating systems, Windows and Lin
This "It has ICX ..." is repeated from a few paragraphs up. I actually suggest moving that content here.

2025-02-14 13:19 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +First, let me share the motivation behind these.
It would be better I think to share the general motivation in fewer words. In-depth paragraphs about both topics before repeating part of the in-depth content in the separate sections on OneAPI and `spin` feels a little off.

2025-02-14 13:20 UTC, rgommers commented
Sorry, only half a review, hit submit too early - more comments coming.

2025-02-14 13:35 UTC, rgommers reviewed
It'd be useful to spell check the content - there are a few too many mistakes.

The asciinema videos are still not rendering, I don't understand what is happening in the previews. The videos also need alt text (see checklist in PR description).

2025-02-14 13:35 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Intel offers a complete toolkit for high performance computing (HPC), numerical computing use cases. It goes by the name of [oneAPI](https://www.intel.com/content/www/us/en/developer/tools/oneapi/ove
- I'd use "MKL (Math Kernel Library, ...)" rather than the other way around, since you're also using the abbreviations for ICX & co
- MSVC: we didn't actually add support for it though, so the rationale here is a little off. Try to rephrase to what we actually aimed to do.

2025-02-14 13:35 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Now let's see why we decided to spin from `dev.py` to `spin` (pun inteded). `dev.py` (or `do.py` [[2]](https://labs.quansight.org/blog/the-evolution-of-the-scipy-developer-cli)) was added to improve
I'd say the long-term maintenance load sharing and the familiarity for contributors coming from `numpy` or other project are the main motivations. The paper cuts & bugs are very minor.

2025-02-14 13:35 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Now coming on to the `arpack` issue. Fixing this issue required supporting building SciPy with Intel oneAPI. On Linux the `arpack` issue was already resolved. However, there were some other issues wi
You may want to link to https://github.com/opencollab/arpack-ng, most readers won't know what ARPACK is.

2025-02-14 13:35 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +The final checkpoint for Intel oneAPI was `CI: Test icx + icpx + ifx + MKL build of SciPy` [[gh-21254]](https://github.com/scipy/scipy/pull/21254). Here we replaced `gcc` with `icx` and `g++` with `i
The last two sentences are not a very good ending. Try to say why we stopped (e.g., "the effort wasn't justified by ..."), otherwise it leaves the reader wondering.

2025-02-14 13:35 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Now let's see why we decided to spin from `dev.py` to `spin` (pun inteded). `dev.py` (or `do.py` [[2]](https://labs.quansight.org/blog/the-evolution-of-the-scipy-developer-cli)) was added to improve
Also, it'd be good to say somehting like "`dev.py` was a major improvement in development workflow, and came before `spin`. `spin` took its inspiration [in large part](https://github.com/scientific-python/spin/?tab=readme-ov-file#history) from `dev.py`, and generalized its interface to work with more projects without customization as heavy as `dev.py` has for SciPy".

2025-02-14 13:35 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +We decided to shift to `spin` because of the several issues reported in `dev.py`. For example, [doit interfering with command history of pdb] [[gh-16452]](https://github.com/scipy/scipy/issues/16452)
repeating grammar issue, so commenting: it's "fewer bugs" rather than "lesser bugs" (check for "lesser" in the whole post please)

2025-02-21 07:00 UTC, czgdp1807 commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Intel offers a complete toolkit for high performance computing (HPC), numerical computing use cases. It goes by the name of [oneAPI](https://www.intel.com/content/www/us/en/developer/tools/oneapi/ove
I think MSVC wasn't tested on CI before our work, right? On Windows we used clang for CI testing. So may be a better line can be, "Since it is the de-facto compiler for C/C++ on Windows, we added CI jobs for testing SciPy compilation with MSVC"

2025-02-21 11:58 UTC, czgdp1807 commented
@rgommers Taking into account your reviews, I have done the following,

1. Improvised the language of the blog post content. Should be more lucid to read now.
2. Added short text descriptions for asciinema videos.
3. The videos are now linked to my `asciinema` account, so they should load. If not then we have the text descriptions.
4. Fixed spelling mistakes via Google docs.

Please go through it now and let me know your experience. Drop in any reviews where you think changes are needed.

Thank you.

2025-03-03 13:00 UTC, pavithraes requested changes
@czgdp1807 Thanks for authoring this post, and for your patience with the review. It's a good read, and I learnt some new things! I've shared a few narrative suggestions. 

The videos not rendering in the preview is a blocker. I'm not familiar with asciinema, and need to look into it.

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +In this blog post, we’ll discuss the improvements we made to enhance the developer experience at SciPy. Our work focused on two key areas:
```suggestion
Over the past year, we worked on enhancing the development experience of SciPy. We focused on two key areas:
```

The start feels a little abrupt, hence this suggestion for a softer introduction.

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +By doing so, we aim to improve the experience for SciPy users who rely on Intel oneAPI as their primary toolkit.
```suggestion
SciPy is heavily used in HPC and numerical computing.
Adding support for SciPy builds with Intel oneAPI was a natural and important step to improve the experience for SciPy users who rely on Intel oneAPI as their primary toolkit.
```

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +`dev.py` (also known as `do.py` [[1]](https://labs.quansight.org/blog/the-evolution-of-the-scipy-developer-cli)) was a significant step forward in improving the development workflow.
```suggestion
`dev.py` (also known as `do.py`, learn more in [The evolution of the SciPy developer CLI](https://labs.quansight.org/blog/the-evolution-of-the-scipy-developer-cli)) was a significant step forward in improving the development workflow.
```

We use this paradigm for footnotes. For links, having descriptive text is more accessible.

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +It includes essential components such as `icx` (for C), `icpx` (for C++), `ifx` (for Fortran), and MKL (Math Kernel Library), which provides optimized mathematical routines like BLAS, LAPACK, and fas
```suggestion
It includes essential components such as `icx` (for C), `icpx` (for C++), `ifx` (for Fortran), and [MKL (Math Kernel Library)](https://en.wikipedia.org/wiki/Math_Kernel_Library), which provides optimized mathematical routines like BLAS, LAPACK, and fast FFTs.
```

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +The next major hurdle involved the [`arpack`](https://github.com/opencollab/arpack-ng) issue, which required full Intel oneAPI support to resolve.
I don't think I understand what the "arpack issue" is? Could we link to any issue on the scipy tracker that has more context?

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +In this step, we replaced `gcc` with `icx` and `g++` with `icpx`, and the build successfully passed on Linux. However, on Windows, we were unable to proceed further due to an unresolved import error
```suggestion
In this step, we replaced `gcc` with `icx` and `g++` with `icpx`, and the build successfully passed on Linux.

However, on Windows, we were unable to proceed further due to an unresolved import error with `arpack`. Despite several attempts to fix the issue, all solutions led to dead ends. As it was turning into an unbounded amount of work, we decided to pause the effort on Windows and focus on on more scoped tasks.
```

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +You might wonder, "Why not just update `dev.py` to fix these issues? Why switch to a new third-party tool like `spin`?"
```suggestion
You might wonder, "Why not just update `dev.py` to fix these issues? Why switch to a new third-party tool like `spin`?"
```

Removing since it feels redundant.

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Additionally, any limitations we encounter in `spin` will be addressed through Pull Requests, making it a two-way connection: SciPy benefits from other projects (via `spin`), and those projects benef
```suggestion
Additionally, any limitations we encounter in `spin` will be addressed through upstream contributions to the project, making it a two-way connection: SciPy benefits from other projects contributing to `spin`, and those projects benefit from improvements made by the SciPy team to `spin`.
```

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Here’s a quick comparison of the SciPy build experience with `dev.py` versus `spin`:
The videos don't seem to rendering in the preview: https://labs-git-fork-czgdp1807-feature-intel-oneapi-spin-quansight.vercel.app/blog/intel-oneapi-msvc-spin-scipy

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +It works exactly the same. However, the issues which were there with `dev.py` are not observed with `spin`.
```suggestion
It works exactly the same. Moreover, the issues which were there with `dev.py` are not observed with `spin`.
```

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +As you can see `spin` usage doesn't interfere with PDB's history. This issue was there with `dev.py`.
```suggestion
As you can see `spin` usage doesn't interfere with PDB's history, which was an issue with `dev.py`.
```

2025-03-03 13:00 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +published: February 21, 2025
Just a note to ensure the date is updated before merging this PR.

2025-03-03 15:33 UTC, czgdp1807 commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Here’s a quick comparison of the SciPy build experience with `dev.py` versus `spin`:
I see, I can try https://docs.asciinema.org/manual/server/embedding/#preview-image-link for sharing the videos. `asciinema` will provide an image. If someone clicks it then the videos plays on asciinema website. That should solve the problems showing up due to embedding the player using `script` tag. Let me know if it would work.

2025-03-03 15:39 UTC, czgdp1807 commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +The next major hurdle involved the [`arpack`](https://github.com/opencollab/arpack-ng) issue, which required full Intel oneAPI support to resolve.
I am referring to https://github.com/scipy/scipy/issues/20728. You are right, just linking it here as well should make it clear. I have referred to this issue in lines 42-44.

2025-03-03 15:44 UTC, czgdp1807 commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +The next major hurdle involved the [`arpack`](https://github.com/opencollab/arpack-ng) issue, which required full Intel oneAPI support to resolve.
Done. Let me know if it looks good to you.

2025-03-13 15:54 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Here’s a quick comparison of the SciPy build experience with `dev.py` versus `spin`:
That seems like a pragmatic solution - try it I'd say.

2025-03-20 17:23 UTC, pavithraes commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Here’s a quick comparison of the SciPy build experience with `dev.py` versus `spin`:
I pushed up a commit to do this (please let me know if you're not comfortable with this, and I'll keep it mind for the future), and unblock merging this PR. :)

2025-03-20 17:26 UTC, pavithraes approved these changes
Thanks again! All the comments are addressed. :)

2025-03-20 17:36 UTC, czgdp1807 commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Here’s a quick comparison of the SciPy build experience with `dev.py` versus `spin`:
No worries. Thanks for doing it. :D.

2025-03-20 17:36 UTC, czgdp1807 commented
Less goo and merge? Its been long waiting.

@rgommers

2025-03-20 18:13 UTC, rgommers commented
We may be a week or so away from being able to merge your `spin` PR, so wouldn't it be better to get that done and then tweak this post a bit to say that? It'll read nicer than "almost there, but you can't actually use it yet".

2025-03-20 18:17 UTC, czgdp1807 commented
Sure. Let's go then. That would be an ideal scenario. <3.

2025-04-28 09:20 UTC, czgdp1807 commented
@rgommers @pavithraes Since, https://github.com/scipy/scipy/pull/21674 is merged, this blog post is also ready to go. I made last few changes to the content (see, https://github.com/Quansight/Quansight-website/pull/893/commits/5aea04aea9f6e93d87fe1e9459f3d816f586f05d, https://github.com/Quansight/Quansight-website/pull/893/commits/a0cbea575cae32d042990d8eb0f2a4aa5f374270 and https://github.com/Quansight/Quansight-website/pull/893/commits/243286a36bf33131e5f09437c43ab827b45b5bde). 

I will update the date once this PR is approved for merging.

2025-04-30 14:14 UTC, rgommers approved these changes
Yes, looks ready now. Thanks @czgdp1807, and thanks for all the help @pavithraes!

@czgdp1807 I made one more suggestion, can you please check it? And then update the publication date?

2025-04-30 14:14 UTC, rgommers commented on apps/labs/posts/intel-oneapi-msvc-spin-scipy.md
> +Despite several attempts to fix the issue, all solutions led to dead ends. As it was turning into an unbounded amount of work, we decided to pause the effort on Windows and focus on more scoped tasks
```suggestion
Despite several attempts to fix the issue, all solutions led to dead ends. As it was turning into an unbounded amount of work and the SciPy team is planning to rewrite ARPACK completely in a language other than FORTRAN, we decided to pause the effort on Windows and focus on more scoped tasks.
```

2025-05-02 06:59 UTC, czgdp1807 commented
@rgommers @pavithraes I have applied [this suggestion](https://github.com/Quansight/Quansight-website/pull/893#discussion_r2068742756) and updated the publication date. So let's go and merge this.

2025-05-02 09:28 UTC, merged